// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eweaqbtqzzoxpwfmjinp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3ZWFxYnRxenpveHB3Zm1qaW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzAzMDYsImV4cCI6MjA2ODQ0NjMwNn0.WtQBD8rzu3SpCVDVxN3_0AU4toNi1LVQV3rDTRWHSNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});